export const DEFAULT_MAX_FILE_SIZE = '30'; // **In MB**

// // *** ROLES *** //
// export const MOEI_FP_ADMIN = 'MOEI_FP_ADMIN';
// export const MOEI_FP_MANAGER = 'MOEI_FP_MANAGER';
// export const MOEI_FP_COMMITTEE = 'MOEI_FP_COMMITTEE';
// export const COMMITTEE_SECRETARY = 'COMMITTEE_SECRETARY';
// //Voting Roles
// export const MOEI_FP_CHAIRMAN_VOTING = 'MOEI_FP_CHAIRMAN_VOTING';
// export const MOEI_FP_EMIRATES_FOUNDATION_VOTING = 'MOEI_FP_EMIRATES_FOUNDATION_VOTING';
// export const MOEI_FP_ADNOC_COMMITTEE_VOTING = 'MOEI_FP_ADNOC_COMMITTEE_VOTING';
// export const MOEI_FP_ENOC_COMMITTEE_VOTING = 'MOEI_FP_ENOC_COMMITTEE_VOTING';
// export const MOEI_FP_MOF_COMMITTEE_VOTING = 'MOEI_FP_MOF_COMMITTEE_VOTING';
// //Viewer Roles
// export const MOEI_FP_CHAIRMAN_VIEWER = 'MOEI_FP_CHAIRMAN_VIEWER';
// export const MOEI_FP_ENOC_COMMITTEE_VIEWER = 'MOEI_FP_ENOC_COMMITTEE_VIEWER';
// export const MOEI_FP_ADNOC_COMMITTEE_VIEWER = 'MOEI_FP_ADNOC_COMMITTEE_VIEWER';
// export const MOEI_FP_EMIRATES_FOUNDATION_VIEWER = 'MOEI_FP_EMIRATES_FOUNDATION_VIEWER';
// export const MOEI_FP_MOF_COMMITTEE_VIEWER = 'MOEI_FP_MOF_COMMITTEE_VIEWER';

// export const VITE_MOEI_ROLE_MGMT_DD={"ROLEID": "MOEI_FP_CONFIG", "ROLES": ["MOEI_FP_CONFIG","MOEI_FP_COMMITTEE_VOTING", "MOEI_FP_COMMITTEE_SECRETARY", "MOEI_FP_PUBLIC_RELATIONS", "MOEI_FP_VIEWER"]}
