
export const TASK_NAME = {
  FUEL_PRICE_RESUBMIT: "Update Fuel Pricing Configurations",
  FUEL_PRICING_ADJUST_PRICE:'Adjust Fuel Price',
  FUEL_PRICING_MOM_TASK:'MOM Submission',
  STAKE_HOLDER_REVIEW: 'StakeHolders Review'
};

export const TASK_ACTIONS = {
  APPROVED: "APPROVED",
  MORE_INFO: "MORE_INFO_REQUEST",
  REJECTED: "REJECTED",
  SUBMITTED: "SUBMIT",
  RESUBMIT: "RESUBMIT"
}
export const TASK_BUTTONS={
  APPROVE:'APPROVE',
  APPROVED:'APPROVED',
  REJECT:'REJECT',
  CHANGE_REQ:'CHANGE_REQ',
  NEED_MORE_INFORMATION:'NEED_MORE_INFORMATION'
}

export const UPDATE_REQUEST_DETAILS_TASK_ACTIONS = [
  "RESUBMIT","SUBMIT","ADD_ADJUSTMENTS", "APPROVED"
]